const checker = require("license-checker");
const path = require("path");
const thisPkg = require("../package.json");

checker.init(
  {
    start: ".",
    customPath: "licenseText",
    excludePackages: `${thisPkg.name}@${thisPkg.version}`
  },
  (err, pkgs) => {
    if (err) {
      console.log(err);
      process.exit(1);
    }

    var h = "LICENSES OF THE DEPENDENCIES";
    var padLen = (80 - h.length) / 2;
    console.log("=".repeat(padLen) + h + "=".repeat(80 - h.length - padLen));
    console.log("Generated by", path.relative(".", __filename));

    Object.entries(pkgs).forEach(([module, info]) => {
      console.log("=".repeat(80));
      console.log(module);
      info.repository && console.log("- repository: " + info.repository);
      info.copyright && console.log("- copyright:  " + info.copyright);
      console.log("-".repeat(80));
      info.licenseText || process.exit(1);
      console.log(info.licenseText.replace(/\r\n/g, "\n"));
    });
    console.log("=".repeat(80));
  }
);
